soruCevapPortali/Controllers/SoruController.cs
using Humanizer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using soruCevapPortali.Models;
using soruCevapPortali.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace soruCevapPortali.Controllers
{
    public class SoruController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        public SoruController(AppDbContext dbContext, ILogger<HomeController> logger, UserManager<AppUser> userManager)
        {
            _dbContext = dbContext;
            _logger = logger;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var sorular = _dbContext.Questions.ToList();
            return View(sorular);
        }

        public IActionResult soruEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult soruEkle(QuestionModel yeniSoru)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Sorular newQuestion = new Sorular
                    {
                        Title = yeniSoru.Title,
                        Content = yeniSoru.Content,
                        CreatedAt = DateTime.Now,
                        UserId = _userManager.GetUserId(User),
                };
                    _dbContext.Questions.Add(newQuestion);
                    _dbContext.SaveChanges();
                    _logger.LogInformation("Veri Tabanı Kaydı Oldu");

                }
                catch
                {
                    _logger.LogInformation("Veri Tabanı Kaydı OlMADI");

                }
            

            }
            else
            {
                _logger.LogInformation("ModelState Çalışmadı");
            }
            return RedirectToAction("soruCevapGorunum");
        }

        private int GetLoggedInUserId()
        {
            return 1;
        }
        public IActionResult sorular()
        {
            var sorular = GetSorular();
            var cevaplar = GetCevaplar();

            var model = new QuestionModel
            {
            };

            return View(model);
        }

        private List<Sorular> GetSorular()
        {
            return new List<Sorular>
        {
            new Sorular { QuestionId = 1, Content = "Soru 1", Title = "Soru 1 içeriği" },
            new Sorular { QuestionId = 2, Content = "Soru 2", Title = "Soru 2 içeriği" }
        };
        }

        private List<Cevaplar> GetCevaplar()
        {
            return new List<Cevaplar>
        {
            new Cevaplar { AnswerId = 1, Content = "Cevap 1 içeriği" },
            new Cevaplar { AnswerId = 2, Content = "Cevap 2 içeriği" }
        };
        }
        public IActionResult soruCevapGorunum()
        {
            var questions = _dbContext.Questions.ToList();
            var answers = _dbContext.Answers.ToList();

            var combinedViewModel = new CiftOzellikModel
            {

                Questions = questions.Select(question => new QuestionModel
                {
                    QuestionId = question.QuestionId,
                    Title = question.Title,
                    Content = question.Content,
                    CreatedAt = DateTime.Now,
                }).ToList(),
                Answers = answers.Select(answer => new AnswerModel
                {
                    AnswerId = answer.AnswerId,
                    Content = answer.Content,
                    CreatedAt = DateTime.Now,
                    QuestionId = answer.QuestionId,
                }).ToList(),
            };
            return View(combinedViewModel); 
        }

        public IActionResult CombinedView()
        {
            

            return View();
        }

        public IActionResult CevapEkle(int id)
        {

            var question = _dbContext.Questions
                .Where(a => a.QuestionId == id)
                .FirstOrDefault();
            var answerModel = new AnswerModel()
            {
                QuestionId = id,
                QuestionTitle = question.Title,
                QuestionContent = question.Content,

            };
            return View(answerModel);
        }

        [HttpPost]
        public IActionResult CevapEkle(AnswerModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userId = _userManager.GetUserId(User);

                    if (userId != null)
                    {
                        var answer = new Cevaplar
                        {
                            QuestionId = model.QuestionId,
                            Content = model.Content,
                            CreatedAt = DateTime.Now,
                            UserId = userId,
                        };

                        _dbContext.Answers.Add(answer);
                        var affectedRows = _dbContext.SaveChanges();

                        if (affectedRows > 0)
                        {
                            _logger.LogInformation("Cevaplar veritabanına başarıyla kaydedildi.");
                        }
                        else
                        {
                            _logger.LogWarning("Veritabanına kayıt eklenirken bir hata oluştu.");
                        }
                    }
                    else
                    {
                        _logger.LogError("Kullanıcı kimliği alınamadı.");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Veritabanına kayıt eklenirken bir hata oluştu: {ex.Message}");
                }
            }
            else
            {
                _logger.LogWarning("Model geçerli değil. Validasyon hatası.");
            }

            return RedirectToAction("soruCevapGorunum");
        }
    }
}

soruCevapPortali/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - soruCevapPortali</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/soruCevapPortali.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Soru Cevap Portalı</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <partial name="_MenuPartial"></partial>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <a href="c:\users\oguzh\desktop\aspfinal\sorucevapportali\views\home\login.cshtml"></a>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - soruCevapPortali - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

soruCevapPortali/Views/Shared/_MenuPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
    </li>
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetUserList">Üyeler</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetRoleList">Roller</a>
            </li>
        }
    }

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Soru" asp-action="soruEkle">Soru Ekle</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Soru" asp-action="soruCevapGorunum">Sorularınız</a>
    </li>
</ul>